name: Build CEF

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to build:'
        type: string
        required: true
        default: 'em-7151'
      arch:
        description: 'Architecture'
        required: true
        default: 'x86'
        type: choice
        options:
        - x86
        - x64
      clean:
        description: 'Force clean'
        type: boolean
        required: true
        default: false      

jobs:
  build:
    timeout-minutes: 1440
    
    runs-on:
      group: Metal

    steps:
      - name: Download automate-git.py
        shell: cmd
        run: curl -O https://raw.githubusercontent.com/emclient/cef/refs/heads/${{ inputs.branch }}/tools/automate/automate-git.py

      - name: Build CEF
        shell: cmd
        run: |
          set GN_DEFINES=is_official_build=true
          set GYP_MSVS_VERSION=2022
          set CEF_ARCHIVE_FORMAT=tar.bz2
          python automate-git.py --download-dir=${{ github.workspace }} --url=https://github.com/emclient/cef.git --branch=${{ inputs.branch }} --minimal-distrib --client-distrib ${{ inputs.clean && '--force-clean' || '--force-build' }} ${{ inputs.arch == 'x64' && '--x64-build' || '' }} --with-pgo-profiles

      - name: Upload binaries
        uses: actions/upload-artifact@v4
        with:
          compression-level: 0
          path: ${{ github.workspace }}/cef/chromium/src/cef/binary_distrib/*.tar.bz2
